version: '3'

services:
  
  php:
    volumes:
      - ../data/www:/www
    env_file:
      - ../images/php/php.dev.env
    logging:
      driver: "json-file"

  db:
    ports:
      - "$DB_PORT:3306"
    env_file:
      - ../images/mysql/db.dev.env
    networks:
      - private
      - public
    logging:
      driver: "json-file"

  nginx:
    env_file: 
      - ../images/nginx/proxy.dev.env
    ports: 
      - "$PROXY_HTTP:80"
      - "$PROXY_HTTPS:443"
    volumes:
      - ../data/www:/www
    networks:
      - private
      - loadbalancer0
      - public
    logging:
      driver: "json-file"

  node:
    env_file: 
      - ../images/node/node.env
    ports: 
      - "$FRONTEND_HTTP:3000"
    volumes:
      - ../data/app:/app
    networks:
      - private
      - loadbalancer0
      - public
    logging:
      driver: "json-file"

  owncloud:
    image: owncloud
    ports:
      - 8080:80