version: '2'

services:
  
  php7:
    volumes:
      - ../data/www:/www
    env_file:
      - ../images/php/php.dev.env
    logging:
      driver: "json-file"

  legacy:
    volumes:
      - ../data/www:/www
    env_file:
      - ../images/php/php.dev.env
    logging:
      driver: "json-file"

  phpa:
    volumes:
      - ../data/www:/www
    env_file:
      - ../images/php/php.dev.env
    logging:
      driver: "json-file"

  db:
    ports:
      - "$DB_PORT:3306"
    env_file:
      - ../images/mysql/db.dev.env
    networks:
      - tier_3
      - tier_2
    logging:
      driver: "json-file"

  nginx:
    env_file: 
      - ../images/nginx/proxy.dev.env
    ports: 
      - "$PROXY_HTTP:80"
      - "$PROXY_HTTPS:443"
    volumes:
      - ../data/www:/www
    networks:
      - tier_3
      - tier_0
      - tier_2
    logging:
      driver: "json-file"

  node:
    env_file: 
      - ../images/node/node.env
    ports: 
      - "$FRONTEND_HTTP:3000"
    volumes:
      - ../data/app:/app
    networks:
      - tier_3
      - tier_0
      - tier_2
    logging:
      driver: "json-file"