version: '3'

services:

  # BUILD PHP 7
  php7: 
    image: php_$PROJECT_NAME$GIT_BRANCH:$VERSION
    container_name: php_$PROJECT_NAME$GIT_BRANCH
    build: 
      context: ../images/php/7.0
      args:
        PHP_MODS: $PHP_MODS
    restart: always
    tty: true
    expose: 
      - "9000"
    volumes:
      - backend_:/www
    env_file:
      - ../images/php/php.env
    networks:
      - private


  # BUILD PHP 5.6
  legacy: 
    image: php_$PROJECT_NAME$GIT_BRANCH:$VERSION
    container_name: php_$PROJECT_NAME$GIT_BRANCH
    build: 
      context: ../images/php/5.6
      args:
        PHP_MODS: $PHP_MODS
    restart: always
    tty: true
    expose: 
      - "9000"
    volumes:
      - backend_:/www
    env_file:
      - ../images/php/php.env
    networks:
      - private

  # MYSQL 
  mysql:
    image: db_$PROJECT_NAME$GIT_BRANCH:$VERSION
    container_name: db_$PROJECT_NAME$GIT_BRANCH
    build: ../images/mysql
    volumes:
      - mysql_:/var/lib/mysql
    restart: always
    tty: true
    expose: 
      - "3306"
    env_file:
      - ../images/mysql/db.env
    networks:
      - private
  
  # REDIS
  redis:
    image: redis_$PROJECT_NAME$GIT_BRANCH:$VERSION
    container_name: redis_$PROJECT_NAME$GIT_BRANCH
    build: ../images/redis
    volumes:
      - redis_:/data
    expose: 
      - "6379"
    restart: always
    tty: true
    networks:
      - private

  # NODE
  node:
    image: node_$PROJECT_NAME$GIT_BRANCH:$VERSION
    container_name: node_$PROJECT_NAME$GIT_BRANCH
    build: ../images/node
    volumes:
      - frontend_:/app
    expose: 
      - "3000"
    restart: always
    tty: true
    networks:
      - private
      - loadbalancer0

  # nginx
  nginx:
    image: nginx_$PROJECT_NAME$GIT_BRANCH:$VERSION
    build: ../images/nginx
    container_name: nginx_$PROJECT_NAME$GIT_BRANCH
    restart: always
    tty: true
    env_file: 
      - ../images/nginx/proxy.env
    volumes:
      - backend_:/www
    expose: 
      - "80"
      - "443"
    ports: 
      - "$PROXY_HTTP:80"
      - "$PROXY_HTTPS:443"
    networks:
      - private
      - loadbalancer0

volumes:
  mongo_:
  redis_:
  mysql_:
  backend_:
  frontend_:

networks:
  public:
  private:
    internal: true
  loadbalancer0:
    external:
      name: network_loadbalancer0