version: '3'

services:

  legacy:
    volumes:
      - ../data/www:/www
    env_file:
      - ../images/php/php.dev.env
    logging:
      driver: "json-file"

  php7:
    volumes:
      - ../data/www:/www
    env_file:
      - ../images/php/php.dev.env
    logging:
      driver: "json-file"

  mysql:
    ports:
      - "$DB_PORT:3306"
    env_file:
      - ../images/mysql/db.dev.env
    logging:
      driver: "json-file"

  nginx:
    env_file: 
      - ../images/nginx/proxy.dev.env
    volumes:
      - ../data/www:/www
    networks:
      - tier_3
      - tier_1
    logging:
      driver: "json-file"

  node:
    env_file:
      - ../images/node/node.dev.env
    volumes:
      - ../data/app:/app
    networks:
      - tier_3
    logging:
      driver: "json-file"