version: '3'

services:
  
  php:
    volumes:
      - ./data/www:/www
    env_file:
      - ./images/php/php.dev.env
    logging:
      driver: "json-file"

  db:
    ports:
      - "$DB_PORT:3306"
    env_file:
      - ./images/mysql/db.dev.env
    networks:
      - int
      - ext
    logging:
      driver: "json-file"

  nginx:
    env_file: 
      - ./images/nginx/proxy.dev.env
    ports: 
      - "$PROXY_HTTP:80"
      - "$PROXY_HTTPS:443"
    volumes:
      - ./data/www:/www
    networks:
      - int
      - main
      - ext
    logging:
      driver: "json-file"

  owncloud:
    image: owncloud
    ports:
      - 8080:80