version: '3'

services:

  # BUILD PHP 7
  php: 
    build: ./images/php/7.0
    restart: always
    tty: true
    depends_on:
      - redis
      - db
    expose: 
      - "9000"
    volumes:
      - backend_:/www
    links:
      - db:mysql
      - redis
    environment:
      TZ: "Europe/Rome"
      DOCKER: "1"
      DEVELOPMENT: "-1" # -1 because system should work the same in development and production
      MYSQL_ROOT_PASSWORD: "root_password"
      DB_HOST: "mysql"
      DB_NAME: "test"
      DB_USER: "root"
      DB_PASS: ""
      WP_USE_THEMES: "false"
      WP_LANG: "it_IT"
      WP_POST_REVISIONS: "false"
      PROJECT_NAME: "test"
      APP_ID: "aeriawork"
      ENV: "local"
      HTTP_HOST: "localhost"
      PUBLIC_URL: "http://aeriawork.vanadio.dev"
    networks:
      - ext
      - int

  # MYSQL 
  db:
    build: ./images/mysql
    volumes:
      - mysql_:/var/lib/mysql
      - mysql__:/var/log/mysql
    restart: always
    tty: true
    expose: 
      - "3306"
    ports:
      - "8836:3306"
    environment:
      TZ: "Europe/Rome"
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_DATABASE: "test"
    networks:
      - int
  
  # REDIS
  redis:
    build: ./images/redis
    volumes:
      - redis_:/data
    expose: 
      - "6379"
    restart: always
    tty: true
    networks:
      - int

  # nginx
  proxy:
    build: ./images/nginx
    restart: always
    tty: true
    environment: 
      TZ: "Europe/Rome"
      WORKDIR: "/www"
      SSLOPTS: "-w /www -d localhost -d 127.0.0.1"
      ENVIRONMENT: "DEVELOPMENT"
      DOMAIN: "localhost"
    volumes:
      - backend_:/www
      - nginx__:/var/log/nginx
    depends_on:
      - php
    links:
      - db:mysql
      - php:php7
    expose: 
      - "80"
      - "443"
    ports: 
      - "8880:80"
      - "8443:443"
    networks:
      - ext
      - int

volumes: # 1 underscore, data voluem. 2 underscore, logs volume
  mongo_: 
  redis_:
  mysql_:
  backend_:
  frontend_:
  nginx__:
  mysql__:

networks:
  ext:
  int:
    internal: true