version: '3'

services:
  
  php:
    volumes:
      - ./data/www:/www
    env_file:
      - ./images/php/php.dev.env

  db:
    ports:
      - "$DB_PORT:3306"
    env_file:
      - ./images/mysql/db.dev.env
    networks:
      - int
      - ext

  proxy:
    env_file: 
      - ./images/nginx/proxy.dev.env
    ports: 
      - "$PROXY_HTTP:80"
      - "$PROXY_HTTPS:443"
    networks:
      - int
      - main
      - ext