version: '3'

services:

  # BUILD PHP 7
  php: 
   build: ./images/php/7.0
   #restart: always
   #tty: true
   depends_on:
     - redis
     - db
   expose: 
     - "9000"
   volumes:
     - data:/www
     - logs:/var/log/php7.0-fpm.log
     - conf:/etc/php/7.0/fpm/php.ini
   links:
     - db:mysql
     - redis
   environment:
     TZ: "Europe/Rome"
     DEVELOPMENT: "true"
     MYSQL_ROOT_PASSWORD: "root_password"
     MYSQL_USER: "admin"
     MYSQL_PASSWORD: "admin"
     MYSQL_DATABASE: "test"
   networks:
     - ext

  # BUILD HHVM
  hhvm: 
   build: ./images/hhvm
   #restart: always
   #tty: true
   depends_on:
     - redis
     - db
   expose: 
     - "9000"
   volumes:
     - data:/www
     - logs:/var/log/php7.0-fpm.log
     - conf:/etc/hhvm/php.ini
     - conf:/etc/hhvm/server.ini
   links:
     - db:mysql
     - redis
   environment:
     TZ: "Europe/Rome"
     DEVELOPMENT: "true"
     MYSQL_ROOT_PASSWORD: "root_password"
     MYSQL_USER: "admin"
     MYSQL_PASSWORD: "admin"
     MYSQL_DATABASE: "test"
   networks:
     - ext
  
  # BUILD NODEJS 
  # use pm2 optionally
  node: 
   build: ./images/node
   #restart: always
   #tty: true
   expose: 
     - "27017"
   volumes:
     - data:/app
   depends_on:
     - mongo
   environment:
     PORT: "3000"
   networks:
     - ext # giving it external access for eventual API calls to third parties

  # MYSQL 
  db:
   image: mysql:5.7
   volumes:
     - data:/var/lib/mysql
     - logs:/var/log/mysql
     - conf:/etc/mysql:ro
   #restart: always
   expose: 
     - "3306"
   ports:
     - "8836:3306"
   environment:
     TZ: "Europe/Rome"
     MYSQL_ROOT_PASSWORD: "root_password"
     MYSQL_USER: "admin"
     MYSQL_PASSWORD: "admin"
     MYSQL_DATABASE: "test"
  
  # mongodb 
  mongo:
   image: mongo:latest
   #restart: always
   volumes:
     - data:/data/db
     #- conf:/data/configdb
   expose: 
     - "27017"
  
  # REDIS
  redis:
   image: redis
   volumes:
     - data:/data
     - conf:/usr/local/etc/redis/redis.conf
   expose: 
     - "6379"
   command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
   #restart: always

  # nginx
  proxy:
    build: ./images/nginx
    #restart: always
    #tty: true
    environment: 
     TZ: "Europe/Rome"
     WORKDIR: "/www"
     SSLOPTS: "-w /www/7.0 -d localhost -d 127.0.0.1"
     ENVIRONMENT: "DEVELOPMENT"
     DOMAIN: "localhost"
    volumes:
     - data:/www
     - logs:/var/log/nginx
     - conf:/etc/nginx:ro
    depends_on:
     - legacy
     - php
     - hhvm
    links:
     - db:mysql
     - legacy:legacy
     - php:php7
     - hhvm
    expose: 
     - "80"
     - "443"
    ports: 
     - "8880:80"
     - "8443:443"
    networks:
     - ext

volumes:
  data:
  logs:
  conf:

networks: 
  ext: