version: '3'

services:

  # BUILD PHP 7
  php: 
    build: ./images/php/7.0
    restart: always
    tty: true
    depends_on:
      - redis
      - db
    expose: 
      - "9000"
    volumes:
      - backend_:/www
    links:
      - db:mysql
      - redis
    env_file:
      - ./images/php/php.env
    networks:
      - ext
      - int
    healthcheck:
      test: sh
      interval: 1m30s
      timeout: 10s
      retries: 3
    deploy:
      mode: replicated
      replicas: 6
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: pause
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      resources:
        limits:
          cpus: '0.001'
          memory: 512M
        reservations:
          cpus: '0.0001'
          memory: 200M

  # MYSQL 
  db:
    build: ./images/mysql
    volumes:
      - mysql_:/var/lib/mysql
      - mysql__:/var/log/mysql
    restart: always
    tty: true
    expose: 
      - "3306"
    ports:
      - "$DB_PORT:3306"
    env_file:
      - ./images/mysql/db.env
    networks:
      - int
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      resources:
        limits:
          cpus: '0'
          memory: 1.5G
        reservations:
          cpus: '0.0001'
          memory: 1G
  
  # REDIS
  redis:
    build: ./images/redis
    volumes:
      - redis_:/data
    expose: 
      - "6379"
    restart: always
    tty: true
    networks:
      - int
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      resources:
        limits:
          cpus: '0.001'
          memory: 1G
        reservations:
          cpus: '0.0001'
          memory: 1G

  # nginx
  nginx:
    build: ./images/nginx
    restart: always
    tty: true
    env_file: 
      - ./images/nginx/proxy.env
    volumes:
      - backend_:/www
      - nginx__:/var/log/nginx
    depends_on:
      - php
    links:
      - db:mysql
      - php:php7
    expose: 
      - "80"
      - "443"
    ports: 
      - "$PROXY_HTTP:80"
      - "$PROXY_HTTPS:443"
    networks:
      - int
      - ext
    healthcheck:
      test: sh
      interval: 1m30s
      timeout: 10s
      retries: 3
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      resources:
        limits:
          cpus: '0.001'
          memory: 200M
        reservations:
          cpus: '0.0001'
          memory: 200M

volumes: # 1 underscore, data voluem. 2 underscore, logs volume
  mongo_: 
  redis_:
  mysql_:
  backend_:
  frontend_:
  nginx__:
  mysql__:
  proxy__:

networks:
  ext:
  int:
    internal: true