version: '2'

services:
  # BUILD PHP 7
  php: 
   build: ./images/php/7.0
   restart: always
   tty: true
   depends_on:
     - redis
   expose: 
     - "9000"
   volumes: 
     - ./data/www:/www
     - ./conf/php-7.0/php.ini:/etc/php/7.0/fpm/php.ini
     - ./logs/php/php7.0-fpm.log:/var/log/php7.0-fpm.log
   links:
     - db:mysql
     - redis
   networks:
     - int
     - ext

  # BUILD PHP 5.6
  legacy: 
   build: ./images/php/5.6
   restart: always
   tty: true
   depends_on:
     - redis
   expose: 
     - "9001"
   volumes: 
     - ./data/www:/www
     - ./conf/php-5.6/php.ini:/etc/php/5.6/fpm/php.ini
     - ./logs/php/php5.6-fpm.log:/var/log/php5.6-fpm.log
   links:
     - db:mysql
     - redis
   networks:
     - int
     - ext

  # MYSQL 
  db:
   image: mysql:5.7
   volumes:
     - ./data/mysql:/var/lib/mysql
     - ./conf/mysql:/etc/mysql:ro
     - ./logs/mysql:/var/log/mysql
   restart: always
   expose: 
     - "3306"
   environment:
     MYSQL_ROOT_PASSWORD: "root_password"
     MYSQL_USER: "admin"
     MYSQL_PASSWORD: "admin"
     MYSQL_DATABASE: "test"
   networks:
    - int
  
  # REDIS
  redis:
   image: redis
   expose: 
    - "6379"
   volumes: 
    - ./data/redis:/data
    - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
   command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
   restart: always
   networks:
     - int

  # # NGINX 
  proxy:
   depends_on:
     - db
     - php
   links:
     - db:mysql
     - php:php7
   image: nginx:alpine
   volumes: 
     - ./conf/nginx:/etc/nginx:ro
     - ./data/www:/www:ro
     - ./logs/nginx:/var/log/nginx
   restart: always
   ports:
     - "8880:80"
     - "8443:443"
   networks:
     - int
     - ext

networks: 
  int:
    internal: true
  ext: