version: '3'

services:

  # BUILD PHP 7
  php: 
    image: php_$PROJECT_NAME:$VERSION
    container_name: php_$PROJECT_NAME
    build: ./images/php/7.0
    restart: always
    tty: true
    depends_on:
      - redis
      - db
    expose: 
      - "9000"
    volumes:
      - backend_:/www
    links:
      - db:mysql
      - redis
    env_file:
      - ./images/php/php.env
    networks:
      - ext
      - int

  # MYSQL 
  db:
    image: db_$PROJECT_NAME:$VERSION
    container_name: db_$PROJECT_NAME
    build: ./images/mysql
    volumes:
      - mysql_:/var/lib/mysql
      - mysql__:/var/log/mysql
    restart: always
    tty: true
    expose: 
      - "3306"
    env_file:
      - ./images/mysql/db.env
    networks:
      - int
  
  # REDIS
  redis:
    image: redis_$PROJECT_NAME:$VERSION
    container_name: redis_$PROJECT_NAME
    build: ./images/redis
    volumes:
      - redis_:/data
    expose: 
      - "6379"
    restart: always
    tty: true
    networks:
      - int

  # nginx
  nginx:
    image: nginx_$PROJECT_NAME:$VERSION
    build: ./images/nginx
    container_name: nginx_$PROJECT_NAME
    restart: always
    tty: true
    env_file: 
      - ./images/nginx/proxy.env
    volumes:
      - backend_:/www
      - nginx__:/var/log/nginx
    depends_on:
      - php
    links:
      - db:mysql
      - php:php7
    expose: 
      - "80"
      - "443"
    ports: 
      - "$PROXY_HTTP:80"
      - "$PROXY_HTTPS:443"
    networks:
      - int
      - main

volumes: # 1 underscore, data voluem. 2 underscore, logs volume
  mongo_: 
  redis_:
  mysql_:
  backend_:
  frontend_:
  nginx__:
  mysql__:
  proxy__:

networks:
  ext:
  int:
    internal: true
  main:
    external:
      name: network_main