version: "3"

networks: 
  loadbalancer0:
    driver: "bridge"

volumes:
  nginx_:
  certs_:

services:

  dummy:
    container_name: lb_haproxy_global
    image: alpine:latest
    networks:
      - loadbalancer0
    command: sh

  lb_nginx:
    image: nginx
    container_name: lb_nginx
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - loadbalancer0
    volumes:
      - nginx_:/etc/nginx/conf.d

  lb_dockergen:
    image: jwilder/docker-gen
    container_name: lb_dockergen
    networks:
      - loadbalancer0
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_:/etc/nginx/conf.d

  lb_letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: lb_letsencrypt
    networks:
      - loadbalancer0
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs_:/etc/nginx/certs
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=lb_nginx

